<?php

// config for ChrisReedIO/MonacoEditor
return [
    'default_language' => 'blade',
    'default_theme' => 'vs-dark',
    'default_min_height' => '16rem',
    'defaults' => [
        'fontSize' => 14,
        'lineNumbers' => 'on',
        'scrollBeyondLastLine' => false,
        'minimap' => ['enabled' => false],
    ],
    'blade' => [
        'keywords' => [
            'if',
            'elseif',
            'else',
            'endif',
            'for',
            'endfor',
            'foreach',
            'endforeach',
            'while',
            'endwhile',
            'isset',
            'empty',
            'include',
            'extends',
            'section',
            'endsection',
            'yield',
            'stack',
            'push',
            'endpush',
            'endphp',
            'php',
            'csrf',
            'method',
            'can',
            'endcan',
            'auth',
            'guest',
            'unless',
            'endunless',
        ],
        'directives' => [
            'if',
            'elseif',
            'else',
            'endif',
            'for',
            'endfor',
            'foreach',
            'endforeach',
            'while',
            'endwhile',
            'isset',
            'empty',
            'include',
            'extends',
            'section',
            'endsection',
            'yield',
            'stack',
            'push',
            'endpush',
            'endphp',
            'php',
            'csrf',
            'method',
            'can',
            'endcan',
            'auth',
            'guest',
            'unless',
            'endunless',
        ],
        'patterns' => [],
        'delimiters' => [
            'output' => ['{{', '}}'],
            'raw' => ['{!!', '!!}'],
            'comment' => ['{{--', '--}}'],
        ],
    ],
];
